### PR TITLE
Add group list component

### PR DESCRIPTION
**Pull request by ctcuff**
Adds a list of groups to the sidebar along with some small style changes:
- The sidebar is now a little bit wider (removed the `2.5%` margin)
- The buttons in ant's modals matches the theme of ours
- The Join Group modal is centered
- The title of ant's notification uses `Poppins` while the body uses `DM Sans`
- The box-shadow that appears when you hover over an image on the image grid is applied to the image instead of the container
- Temporarily removed the initial scale animation for the main page when it mounts

### CODE REVIEW

**Review by suneettipirneni — APPROVED** [review]
Looks good!

**Review by ElbertTse — APPROVED** [review]
Looks good but I noticed that the button borders stay highlighted after closing the modal that opened them. Not sure if its something we can fix though

**Comment by ctcuff** [comment]
> Looks good but I noticed that the button borders stay highlighted after closing the modal that opened them. Not sure if its something we can fix though

Good point! That's just the browser adding an outline to the element when it's it focus. Can be removed with
```css
:focus {
  outline: none;
}
```
but I felt like it was probably best to just keep the default behavior, open to other opinions though

**Comment by ElbertTse** [comment]
> > Looks good but I noticed that the button borders stay highlighted after closing the modal that opened them. Not sure if its something we can fix though
> 
> Good point! That's just the browser adding an outline to the element when it's it focus. Can be removed with
> 
> ```css
> :focus {
>   outline: none;
> }
> ```
> 
> but I felt like it was probably best to just keep the default behavior, open to other opinions though

I'd prefer removing it but I can go either way

**Comment by ctcuff** [comment]
> I'd prefer removing it but I can go either way

👍

**Pull request merged**
