### PR TITLE
Make some ant components match our aesthetic

### PR DESCRIPTION
**Pull request by suneettipirneni**
Made some modifications to the modal buttons as well as the inputs.

### CODE REVIEW

**Review by ctcuff — CHANGES_REQUESTED** [review]
Design looks awesome, just a little thing: the ant button also needs style for the `:disabled` state, similar to ant's default disabled style. I don't think a disabled button should change color on hover.

**Comment by ctcuff** [comment]
Sorry, one last comment!

In `create-group-modal.scss`, `.ant-input-group-addon > .ant-input-search-button` needs `border: 1px solid #1890ff;` took keep it's default look
Screen Shot 2021-04-08 at 2 47 02 PM

Screen Shot 2021-04-08 at 2 49 02 PM

Otherwise should be GTG

**Comment by suneettipirneni** [comment]
> border: 1px solid #1890ff;

done

**Review by ctcuff — APPROVED** [review]
👌

**Pull request merged**
